TaskManagementV1/Views/Shared/Components/UserSessionViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TaskManagementV1.Models.ResponseModels;

namespace TaskManagementV1.Views.Shared.Component
{
    public class UserSessionViewComponent : ViewComponent
    {
        //private readonly IHttpContextAccessor _httpContextAccessor;

        //public UserSessionViewComponent(IHttpContextAccessor httpContextAccessor)
        //{
        //    _httpContextAccessor = httpContextAccessor;
        //}

        public IViewComponentResult Invoke()
        {
            // Retrieve session data (e.g., UserName)
            var token = HttpContext.Session.GetString("Token");
            var UserDetail = HttpContext.Session.GetObjectFromSession<UserInfoDetail>("UserDetail");

            if (string.IsNullOrWhiteSpace(token))
            {
                // If session not found, redirect to login page
                HttpContext.Response.Redirect("/Auth/Index");
                return Content(""); // Return an empty response because redirect is triggered
            }

            // Pass the session value to the view (UserName) to render it
            return View("Default", UserDetail);
        }
    }
}

TaskManagementV1/Views/Shared/_DefaultBlankLayout.cshtml
@{
    bool datatable = (!string.IsNullOrWhiteSpace(ViewBag.datatable) && (ViewBag.datatable == "true" || ViewBag.datatable == "True")) ? true : false;
    bool IsLoginPage = (!string.IsNullOrWhiteSpace(ViewBag.IsLoginPage) && (ViewBag.IsLoginPage == "true" || ViewBag.IsLoginPage == "True")) ? true : false;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task Management</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../Theme/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="../Theme/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../Theme/dist/css/adminlte.min.css">
    @if (datatable)
    {
        <!-- DataTables -->
        <link rel="stylesheet" href="../Theme/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="../Theme/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
        <link rel="stylesheet" href="../Theme/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
        @*<link rel="stylesheet" href="../Theme/admin/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">*@
    }
    <link href="~/scripts/common.css" rel="stylesheet" />
</head>
@if (IsLoginPage)
{
    <body class="login-page hold-transition">
        <div class="login-box">
            @RenderBody()
        </div>
        <!-- /.login-box -->
        <!-- jQuery -->
        <script src="../Theme/plugins/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="../Theme/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
        <script src="../Theme/dist/js/adminlte.min.js"></script>
        @if (datatable)
        {
            <!-- DataTables  & Plugins -->
            <script src="../Theme/plugins/datatables/jquery.dataTables.min.js"></script>
            <script src="../Theme/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
            <script src="../Theme/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
            <script src="../Theme/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
            <script src="../Theme/plugins/jszip/jszip.min.js"></script>
            <script src="../Theme/plugins/pdfmake/pdfmake.min.js"></script>
            <script src="../Theme/plugins/pdfmake/vfs_fonts.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/buttons.print.min.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
        }
        <script src="~/theme/jquery.blockui.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="~/scripts/common.js"></script>
        @RenderSection("Scripts", required: false)
    </body>
}
else
{
    <body class="card-body hold-transition">

        @RenderBody()

        <!-- /.login-box -->
        <!-- jQuery -->
        <script src="../Theme/plugins/jquery/jquery.min.js"></script>
        <!-- Bootstrap 4 -->
        <script src="../Theme/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
        <script src="../Theme/dist/js/adminlte.min.js"></script>
        @if (datatable)
        {
            <!-- DataTables  & Plugins -->
            <script src="../Theme/plugins/datatables/jquery.dataTables.min.js"></script>
            <script src="../Theme/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
            <script src="../Theme/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
            <script src="../Theme/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
            <script src="../Theme/plugins/jszip/jszip.min.js"></script>
            <script src="../Theme/plugins/pdfmake/pdfmake.min.js"></script>
            <script src="../Theme/plugins/pdfmake/vfs_fonts.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/buttons.print.min.js"></script>
            <script src="../Theme/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
        }
        <script src="~/theme/jquery.blockui.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="~/scripts/common.js"></script>
        @RenderSection("Scripts", required: false)
    </body>
}
</html>

TaskManagementV1/Views/Shared/_DefaultLayout.cshtml
@using TaskManagementV1.Models.ResponseModels
@{
    bool datatable = (!string.IsNullOrWhiteSpace(ViewBag.datatable) && (ViewBag.datatable == "true" || ViewBag.datatable == "True")) ? true : false;
    bool select2 = (!string.IsNullOrWhiteSpace(ViewBag.select2) && (ViewBag.select2 == "true" || ViewBag.select2 == "True")) ? true : false;
    string PageTitle = !string.IsNullOrWhiteSpace(ViewBag.PageTitle) ? $"- {ViewBag.PageTitle}" : "";
    var UserDetail = Context.Session.GetObjectFromSession<UserInfoDetail>("UserDetail");
    var PermissionList = Context.Session.GetObjectFromSession<List<ActionDetailsList>>("PermissionList");
    if (UserDetail == null)
    {
        Context.Response.Redirect("/Auth/Index");
    }
    string FullName = UserDetail != null ? $"{UserDetail.FirstName} {UserDetail.LastName}" : "";
}
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task Management @PageTitle</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="../Theme/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../Theme/dist/css/adminlte.min.css">

    @if (datatable)
    {
        <!-- DataTables -->
        <link rel="stylesheet" href="../Theme/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="../Theme/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
        <link rel="stylesheet" href="../Theme/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
        @*<link rel="stylesheet" href="../Theme/admin/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">*@
    }
    @if (select2)
    {
        <!-- Select2 -->
        <link rel="stylesheet" href="../Theme/plugins/select2/css/select2.min.css">
        <link rel="stylesheet" href="../Theme/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    }
    <link href="~/scripts/common.css" rel="stylesheet" />
</head>
<body class="hold-transition layout-top-nav fade-in">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
            <div class="container">
                <a href="#" class="navbar-brand">
                    <img src="../Theme/dist/img/reynalogo.png" alt="Reyna Logo" class="brand-image elevation-3" style="opacity: .8">
                    <span class="brand-text font-weight-dark">Task Management</span>
                </a>

                <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                    <!-- Left navbar links -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="/Home/Dashboard" class="nav-link">Dashboard</a>
                        </li>
                        @if (PermissionList.Any(x => x.ActionCode == CommonConstant.Project_View))
                        {
                            <li class="nav-item">
                                <a href="/Project/Index" class="nav-link">Project</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a href="/Task/Index" class="nav-link">Task</a>
                        </li>
                        @if (PermissionList.Any(x => x.ActionCode == CommonConstant.Report_View))
                        {
                            <li class="nav-item">
                                <a href="/Report/Index" class="nav-link">Report</a>
                            </li>
                        }
                    </ul>

                    <!-- SEARCH FORM -->
                    @*  <form class="form-inline ml-0 ml-md-3">
                    <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                    </button>
                    </div>
                    </div>
                    </form> *@
                </div>

                <!-- Right navbar links -->
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    <!-- Messages Dropdown Menu -->
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-toggle="dropdown" href="#">
                            <span><b> @FullName</b>&nbsp;</span>
                            <i class="fas fa-user"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-md2 dropdown-menu-right">
                            <a href="#" class="dropdown-item">
                                <!-- Message Start -->
                                <div class="media">
                                    <img src="../Theme/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                    <div class="media-body">
                                        <h3 class="dropdown-item-title">
                                            @FullName
                                        </h3>
                                        <p class="text-sm">
                                            @await Component.InvokeAsync("UserSession")
                                        </p>
                                    </div>
                                </div>
                                <!-- Message End -->
                            </a>

                            <div class="dropdown-divider"></div>
                            <a href="/Auth/Logout" class="dropdown-item dropdown-footer">Sign out</a>
                        </div>
                    </li>
                    <!-- Notifications Dropdown Menu -->
                </ul>
            </div>
        </nav>
        <!-- /.navbar -->
        <!-- Content Wrapper.Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        @*  <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
        </aside> *@
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            @*   <div class="float-right d-none d-sm-inline">
            Anything you want
            </div> *@
            <!-- Default to the left -->
            <strong>Copyright &copy; 2024-2025 <a href="/Auth/Index">Task Management</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="../Theme/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../Theme/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../Theme/dist/js/adminlte.min.js"></script>
    @if (select2)
    {
        <!-- Select2 -->
        <script src="../Theme/plugins/select2/js/select2.full.min.js"></script>
    }

    @if (datatable)
    {
        <!-- DataTables  & Plugins -->
        <script src="../Theme/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="../Theme/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
        <script src="../Theme/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
        <script src="../Theme/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
        <script src="../Theme/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
        <script src="../Theme/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
        <script src="../Theme/plugins/jszip/jszip.min.js"></script>
        <script src="../Theme/plugins/pdfmake/pdfmake.min.js"></script>
        <script src="../Theme/plugins/pdfmake/vfs_fonts.js"></script>
        <script src="../Theme/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
        <script src="../Theme/plugins/datatables-buttons/js/buttons.print.min.js"></script>
        <script src="../Theme/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    }
    <script src="~/theme/jquery.blockui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/scripts/common.js"></script>
    <script>
        $(document).ready(function () {
            // Get the current page's pathname
            var currentPath = window.location.pathname;

            // Loop through all the navbar links
            $('.navbar-nav .nav-item a').each(function () {
                // Check if the href attribute of the link matches the current page URL
                if (this.href.includes(currentPath) && ! this.href.includes('#')) {
                    // Remove 'active' class from all links
                    $('.navbar-nav .nav-item').removeClass('active');
                    // Add the 'active' class to the clicked link
                    $(this).parent().addClass('active');
                }
            });
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TaskManagementV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagementV1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagementV1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManagementV1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TaskManagementV1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>